### ISSUE TITLE
A minor typing issue

### ISSUE THREAD

**Issue by surinkim** [visvadw/visvadw.github.io#1]
Hi, 
I've found a minor typing issue.

```bash
$ curl -L https://github.com/tdewolff/parse/archive/v2.3.4.zip --output parse-2.3.4.zip
$ unzip parse-2.3.4.zip
$ mv parse-2.3.4.zip parse
```

The bottom line code should be
```bash
$ mv parse-2.3.4 parse
```

Thank you for your valuable article.
I've resolved same problema because of this article.

**Comment by dxps** [comment]
Hi,

Thanks for the feedback and I'm glad that it helped you! 👍 😄 
Updated the notes to removed the typo.
